name: cd_ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rudikrudik/newsbot:latest

  DEPLOY:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: SSH connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull rudikrudik/newsbot
            docker stop newsbot
            docker rm -f newsbot
            docker run -dit --name newsbot rudikrudik/newsbot
            docker exec -d newsbot git clone https://github.com/rudikrudik/news_bot.git /home/
            docker exec newsbot /bin/sh -c 'echo "TOKEN = ${{ secrets.TOKEN}}" >> /home/config.ini'
            docker exec newsbot /bin/sh -c 'echo "CHAT_ID = ${{ secrets.CHAT_ID}}" >> /home/config.ini'            

  START_APP:
    runs-on: ubuntu-latest
    needs: DEPLOY
    steps:
      - name: Run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker exec -d newsbot /usr/bin/python3 /home/main.py
            docker image prune -f